baseurl = "https://peaceful-tor-92061.herokuapp.com/"
languageCode = "en-us"
title = "My React Learning Blogs"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"
theme="vienna"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "rang"
    github = "rangwei"
    gitlab = "Your GitLab username"
    linkedin = "Your LinkedIn username"
    googleplus = "Your Google+ user id"
    facebook = "Your Facebook username"
    reddit = "Your Reddit username"
    hackernews = "Your Hacker News username"
    stackoverflow = "Your Stackoverflow user id (number)"
    keybase = "Your keybase.io username"
    instagram = "Your Instagram username"
    # Disqus shortname
    disqus = "Your disqus shortname"
    # Google Analytics API key.
    ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    mixpanel_api_key = "Your Mixpanel API key"
    author = "RANG"
    avatar = "/path/to/avatar"
    contact = "Your contact link (ex. mailto:foo@example.com)"
    bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "千里之行，始于足下。——老子"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.